### ISSUE TITLE
Premier rendu

### ISSUE THREAD

**Issue by Cluniat** [PolytechLyon/2019-isi3-graph-baccuet_cluniat#9]
Bonjour ! 
On a terminé le premier TP, est-il possible de nous donner votre avis ? 
Merci ! 🎉

**Comment by Slashgear** [comment]
⚠️ Ne touchez pas à mon commentaire 

- Il manque les noms dans le rapport
- c'est quoi ce dossier `index-files` ? Vous avez commit de trucs inutiles non ? Vous pouvez faire le ménage ?
- Certains paramètre sont préfixés par `_` mais pas d'autre, c'est normal ? Pourquoi le faire ? 
-  Vous êtes sur que vos algo de parcours marchent ? 😉 
- Dans cette class, êtes vous obligé de surcharger les fonctions ? 
https://github.com/PolytechLyon/2019-isi3-graph-baccuet_cluniat/blob/f97af25b281601eee19c9b7d3cbaef5cf1d2b972/src/main/java/graph/UndirectedGraph.java#L6 


Prevenez moi quand vous avez pris les retours

**Comment by Cluniat** [comment]
Voici la V2 tenant compte des commentaires (désolé pour index-files on a commit la javadoc ...). 
Les corrections apportées sont-elles suffisantes ?

**Comment by Cluniat** [comment]
@Slashgear

**Comment by Slashgear** [comment]
👍
